//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSINESS
    {
        public Nullable<System.DateTime> INCORP_DATE { get; set; }
        public string NAME { get; set; }
        public string STATE_ID { get; set; }
        public int CUST_ID { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
